services:
    server:
        image: astervia/wacraft-server:v0.1.1
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "6900:6900"
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
            HOST: http://127.0.0.1
            PORT: 6900
            MESSAGE_STATUS_SYNC_TIMEOUT_SECONDS: 10

        networks:
            - main

    client:
        image: astervia/wacraft-client:v0.1.4
        restart: unless-stopped
        depends_on:
            - server
        ports:
            - "80:80"
        env_file:
            - .env
        environment:
            IS_LITE: false
        networks:
            - main

    db:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - main

    # Uncomment this if you are a supporter and is using nodered
    # nodered:
    #   image: astervia/wacraft-nodered:v0.1.0
    #   restart: unless-stopped
    #   depends_on:
    #     - server
    #   ports:
    #     - "1880:1880"
    #   env_file:
    #     - .env
    #   environment:
    #     SERVER_HOST: server
    #   volumes:
    #     - node_red_data:/data
    #   networks:
    #     - main

volumes:
    db_data:
    # Uncomment this if you are a supporter and is using nodered
    # node_red_data:

networks:
    main:
