site_name: wacraft
site_url: https://wacraft.astervia.tech
theme:
    name: material

    # favicon: assets/images/favicon.png
    favicon: assets/images/icon-nobg.png
    logo: assets/images/icon-nobg.png

    features:
        - content.code.copy
        - navigation.footer
    palette:
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/white-balance-sunny
              name: Switch to light mode

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Astervia/wacraft
        - icon: fontawesome/solid/bolt
          link: support/plans.md

nav:
    - Overview: index.md
    - Quick‑Start:
          - Local Setup (5 min): quickstart/local.md
          - Production Deploy (Docker / Vercel): quickstart/production.md
    - Configuration:
          - Getting Meta Credentials: config/meta-setup.md
          - Env Vars Overview: config/env-vars.md
          - Webhook Setup: config/webhook-setup.md
    - Deployment Guides:
          - Deployment Overview: deploy/overview.md
          - Docker Compose: deploy/docker-compose.md # full stack
          - Binary + Vercel (frontend): deploy/binary-vercel.md
          - Node‑RED Integration*: deploy/node-red.md
          # - Supporter‑only Extras*: deploy/supporters.md # deltas + link to donation page
    - Usage Guide:
          - Product Overview: guide/overview.md
          - UI Walkthrough: guide/ui.md
          - FAQs & Troubleshooting: guide/faq.md
    - Reference:
          # - API (auto‑generated): reference/api.md          # embed/redoc‑html export
          - Changelog: reference/changelog.md
    - Support Our Mission:
          - Plans: support/plans.md
          - Consulting Services: support/consulting.md
